### ISSUE TITLE
Build in docker as user

### ISSUE THREAD

**Issue by julianoes** [Dronecode/DronecodeSDK#254]
Currently when we build in docker it uses root and therefore leaves build artefacts with root as the owner. This requires `sudo make distclean` to clean up afterwards outside of docker which is inconvenient.

As @hamishwillee suggests we should build something similar to:
https://dev.px4.io/en/test_and_ci/docker.html
https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_base#L64

**Comment by dagar** [comment]
Docker ENTRYPOINT with this script seems to work well.
https://github.com/PX4/containers/blob/master/docker/px4-dev/scripts/entrypoint.sh

Dockerfile

    # create and start as LOCAL_USER_ID
    COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
    ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

When running the container you need to pass - eLOCAL_USER_ID=$UID and it creates an internal user matching your UID. Otherwise it uses UID 9001, which is still better than root.

**Comment by julianoes** [comment]
@dagar last time I tried to use that it did not work for me, I remember. I'll have to try it again.
